
default: &default
  adapter: postgresql
  encoding: unicode
  username: fedor
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: project_development

test:
  <<: *default
  database: project_test
